// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seedInfo.proto

#include "seedInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_seedInfo_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_seedInfo_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_seedInfo_SeedListEntry_DoNotUse;
}  // namespace protobuf_seedInfo_2eproto

namespace SeedInfoServer {
class seedInfo_SeedListEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<seedInfo_SeedListEntry_DoNotUse>
      _instance;
} _seedInfo_SeedListEntry_DoNotUse_default_instance_;
class seedInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<seedInfo>
      _instance;
} _seedInfo_default_instance_;
}  // namespace SeedInfoServer
namespace protobuf_seedInfo_2eproto {
static void InitDefaultsseedInfo_SeedListEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::SeedInfoServer::_seedInfo_SeedListEntry_DoNotUse_default_instance_;
    new (ptr) ::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse();
  }
  ::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_seedInfo_SeedListEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsseedInfo_SeedListEntry_DoNotUse}, {}};

static void InitDefaultsseedInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::SeedInfoServer::_seedInfo_default_instance_;
    new (ptr) ::SeedInfoServer::seedInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SeedInfoServer::seedInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_seedInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsseedInfo}, {
      &protobuf_seedInfo_2eproto::scc_info_seedInfo_SeedListEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_seedInfo_SeedListEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_seedInfo.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::SeedInfoServer::seedInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::SeedInfoServer::seedInfo, seedlist_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse)},
  { 9, -1, sizeof(::SeedInfoServer::seedInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::SeedInfoServer::_seedInfo_SeedListEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::SeedInfoServer::_seedInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "seedInfo.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016seedInfo.proto\022\016SeedInfoServer\"u\n\010seed"
      "Info\0228\n\010seedList\030\001 \003(\0132&.SeedInfoServer."
      "seedInfo.SeedListEntry\032/\n\rSeedListEntry\022"
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 159);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "seedInfo.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_seedInfo_2eproto
namespace SeedInfoServer {

// ===================================================================

seedInfo_SeedListEntry_DoNotUse::seedInfo_SeedListEntry_DoNotUse() {}
seedInfo_SeedListEntry_DoNotUse::seedInfo_SeedListEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void seedInfo_SeedListEntry_DoNotUse::MergeFrom(const seedInfo_SeedListEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata seedInfo_SeedListEntry_DoNotUse::GetMetadata() const {
  ::protobuf_seedInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_seedInfo_2eproto::file_level_metadata[0];
}
void seedInfo_SeedListEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void seedInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int seedInfo::kSeedListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

seedInfo::seedInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_seedInfo_2eproto::scc_info_seedInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:SeedInfoServer.seedInfo)
}
seedInfo::seedInfo(const seedInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  seedlist_.MergeFrom(from.seedlist_);
  // @@protoc_insertion_point(copy_constructor:SeedInfoServer.seedInfo)
}

void seedInfo::SharedCtor() {
}

seedInfo::~seedInfo() {
  // @@protoc_insertion_point(destructor:SeedInfoServer.seedInfo)
  SharedDtor();
}

void seedInfo::SharedDtor() {
}

void seedInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* seedInfo::descriptor() {
  ::protobuf_seedInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_seedInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const seedInfo& seedInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_seedInfo_2eproto::scc_info_seedInfo.base);
  return *internal_default_instance();
}


void seedInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:SeedInfoServer.seedInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  seedlist_.Clear();
  _internal_metadata_.Clear();
}

bool seedInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SeedInfoServer.seedInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, string> seedList = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          seedInfo_SeedListEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              seedInfo_SeedListEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&seedlist_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "SeedInfoServer.seedInfo.SeedListEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "SeedInfoServer.seedInfo.SeedListEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SeedInfoServer.seedInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SeedInfoServer.seedInfo)
  return false;
#undef DO_
}

void seedInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SeedInfoServer.seedInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> seedList = 1;
  if (!this->seedlist().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "SeedInfoServer.seedInfo.SeedListEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "SeedInfoServer.seedInfo.SeedListEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->seedlist().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->seedlist().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->seedlist().begin();
          it != this->seedlist().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<seedInfo_SeedListEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(seedlist_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<seedInfo_SeedListEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->seedlist().begin();
          it != this->seedlist().end(); ++it) {
        entry.reset(seedlist_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:SeedInfoServer.seedInfo)
}

::google::protobuf::uint8* seedInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:SeedInfoServer.seedInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> seedList = 1;
  if (!this->seedlist().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "SeedInfoServer.seedInfo.SeedListEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "SeedInfoServer.seedInfo.SeedListEntry.value");
      }
    };

    if (deterministic &&
        this->seedlist().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->seedlist().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->seedlist().begin();
          it != this->seedlist().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<seedInfo_SeedListEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(seedlist_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<seedInfo_SeedListEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->seedlist().begin();
          it != this->seedlist().end(); ++it) {
        entry.reset(seedlist_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SeedInfoServer.seedInfo)
  return target;
}

size_t seedInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SeedInfoServer.seedInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, string> seedList = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->seedlist_size());
  {
    ::std::unique_ptr<seedInfo_SeedListEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->seedlist().begin();
        it != this->seedlist().end(); ++it) {
      entry.reset(seedlist_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void seedInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SeedInfoServer.seedInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const seedInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const seedInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SeedInfoServer.seedInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SeedInfoServer.seedInfo)
    MergeFrom(*source);
  }
}

void seedInfo::MergeFrom(const seedInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SeedInfoServer.seedInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  seedlist_.MergeFrom(from.seedlist_);
}

void seedInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SeedInfoServer.seedInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void seedInfo::CopyFrom(const seedInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SeedInfoServer.seedInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool seedInfo::IsInitialized() const {
  return true;
}

void seedInfo::Swap(seedInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void seedInfo::InternalSwap(seedInfo* other) {
  using std::swap;
  seedlist_.Swap(&other->seedlist_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata seedInfo::GetMetadata() const {
  protobuf_seedInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_seedInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace SeedInfoServer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse* Arena::CreateMaybeMessage< ::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::SeedInfoServer::seedInfo* Arena::CreateMaybeMessage< ::SeedInfoServer::seedInfo >(Arena* arena) {
  return Arena::CreateInternal< ::SeedInfoServer::seedInfo >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
