// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seedInfo.proto

#ifndef PROTOBUF_INCLUDED_seedInfo_2eproto
#define PROTOBUF_INCLUDED_seedInfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_seedInfo_2eproto 

namespace protobuf_seedInfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_seedInfo_2eproto
namespace SeedInfoServer {
class seedInfo;
class seedInfoDefaultTypeInternal;
extern seedInfoDefaultTypeInternal _seedInfo_default_instance_;
class seedInfo_SeedListEntry_DoNotUse;
class seedInfo_SeedListEntry_DoNotUseDefaultTypeInternal;
extern seedInfo_SeedListEntry_DoNotUseDefaultTypeInternal _seedInfo_SeedListEntry_DoNotUse_default_instance_;
}  // namespace SeedInfoServer
namespace google {
namespace protobuf {
template<> ::SeedInfoServer::seedInfo* Arena::CreateMaybeMessage<::SeedInfoServer::seedInfo>(Arena*);
template<> ::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse* Arena::CreateMaybeMessage<::SeedInfoServer::seedInfo_SeedListEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace SeedInfoServer {

// ===================================================================

class seedInfo_SeedListEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<seedInfo_SeedListEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<seedInfo_SeedListEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  seedInfo_SeedListEntry_DoNotUse();
  seedInfo_SeedListEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const seedInfo_SeedListEntry_DoNotUse& other);
  static const seedInfo_SeedListEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const seedInfo_SeedListEntry_DoNotUse*>(&_seedInfo_SeedListEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class seedInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SeedInfoServer.seedInfo) */ {
 public:
  seedInfo();
  virtual ~seedInfo();

  seedInfo(const seedInfo& from);

  inline seedInfo& operator=(const seedInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  seedInfo(seedInfo&& from) noexcept
    : seedInfo() {
    *this = ::std::move(from);
  }

  inline seedInfo& operator=(seedInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const seedInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const seedInfo* internal_default_instance() {
    return reinterpret_cast<const seedInfo*>(
               &_seedInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(seedInfo* other);
  friend void swap(seedInfo& a, seedInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline seedInfo* New() const final {
    return CreateMaybeMessage<seedInfo>(NULL);
  }

  seedInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<seedInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const seedInfo& from);
  void MergeFrom(const seedInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(seedInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> seedList = 1;
  int seedlist_size() const;
  void clear_seedlist();
  static const int kSeedListFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      seedlist() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_seedlist();

  // @@protoc_insertion_point(class_scope:SeedInfoServer.seedInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      seedInfo_SeedListEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > seedlist_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_seedInfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// seedInfo

// map<string, string> seedList = 1;
inline int seedInfo::seedlist_size() const {
  return seedlist_.size();
}
inline void seedInfo::clear_seedlist() {
  seedlist_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
seedInfo::seedlist() const {
  // @@protoc_insertion_point(field_map:SeedInfoServer.seedInfo.seedList)
  return seedlist_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
seedInfo::mutable_seedlist() {
  // @@protoc_insertion_point(field_mutable_map:SeedInfoServer.seedInfo.seedList)
  return seedlist_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SeedInfoServer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_seedInfo_2eproto
